language: objective-c
cache:
- bundler
- cocoapods
xcode_workspace: PlaidLink.xcworkspace
podfile: Tests/Podfile
xcode_scheme: ios
xcode_sdk: iphonesimulator9.0
osx_image: xcode7
before_install:
- gem install cocoapods -v '0.39.0'
script:
- xctool -workspace PlaidLinkTests.xcworkspace -scheme ios build -sdk iphonesimulator9.0
