language: objective-c
cache:
- bundler
- cocoapods
xcode_workspace: PlaidLink.xcworkspace
podfile: Podfile
xcode_scheme: PlaidLink
xcode_sdk: iphonesimulator9.0
osx_image: xcode7
before_install:
- gem install cocoapods -v '0.39.0'
script:
- xctool -workspace PlaidLink.xcworkspace -scheme PlaidLink build
